name: Redis EC2 Test

on:
  workflow_dispatch:  # allows manual run
  #schedule:
    #- cron: "*/5 * * * *"  # runs every 5 minutes

jobs:
  redis-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Redis client
      run: pip install redis

    - name: Run Redis stress test
      env:
        REDIS_HOST: ${{ secrets.REDIS_HOST }}  # Reference to the secret
      run: |
        python redis_test.py
